/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Camera: typeof import('./src/components/Camera.vue')['default']
    Compare: typeof import('./src/components/Compare.vue')['default']
    Credits: typeof import('./src/components/Credits.vue')['default']
    DialogDownload: typeof import('./src/components/DialogDownload.vue')['default']
    DialogGridAlign: typeof import('./src/components/DialogGridAlign.vue')['default']
    DialogScan: typeof import('./src/components/DialogScan.vue')['default']
    Generator: typeof import('./src/components/Generator.vue')['default']
    GridLines: typeof import('./src/components/GridLines.vue')['default']
    ImageDrop: typeof import('./src/components/ImageDrop.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    OptionCheckbox: typeof import('./src/components/OptionCheckbox.vue')['default']
    OptionColor: typeof import('./src/components/OptionColor.vue')['default']
    OptionItem: typeof import('./src/components/OptionItem.vue')['default']
    OptionSelectGroup: typeof import('./src/components/OptionSelectGroup.vue')['default']
    OptionSlider: typeof import('./src/components/OptionSlider.vue')['default']
    SafariWarning: typeof import('./src/components/SafariWarning.vue')['default']
    Scanner: typeof import('./src/components/Scanner.vue')['default']
    SegmentViewer: typeof import('./src/components/SegmentViewer.vue')['default']
    SettingsCorrection: typeof import('./src/components/SettingsCorrection.vue')['default']
    SettingsMargin: typeof import('./src/components/SettingsMargin.vue')['default']
    SettingsMarkerStyle: typeof import('./src/components/SettingsMarkerStyle.vue')['default']
    SettingsRandomRange: typeof import('./src/components/SettingsRandomRange.vue')['default']
    StateProvider: typeof import('./src/components/StateProvider.vue')['default']
  }
}
